apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/banjoSolomon/Argocd.git'
    targetRevision: HEAD
    path: 'gitops'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
