apiVersion: v1
kind: Service
metadata:
  name: hello-frontend
  namespace: default   
spec:
  selector:
    app: hello-frontend
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
